---
- name: Install metric exporter on all hosts
  hosts: all
  become: yes
  become_user: user
  ignore_errors: yes
  tasks:

    - name: Check If Image exists
      register: Image_exists
      ansible.builtin.shell:
        cmd: test -f /tmp/node_exporter.tgz

    - name: Copy metric exporter image
      register: Image_copy
      when: Image_exists.rc != 0
      ansible.builtin.copy:
        src: ./node_exporter.tgz
        dest: /tmp/node_exporter.tgz

    - name: Load Image
      register: Load_image
      when: Image_copy.rc != 0
      ansible.builtin.shell:
        cmd: docker load -i /tmp/node_exporter.tgz
