---
version: '3.8'

services:
  node_exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'