---
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ~/Prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ~/Prometheus/data:/prometheus